exports.accommodation = {
  message: "성공",
  data: {
    id: 2,
    name: "Accommodation2",
    type: 0,
    address: "제주특별자치도 서귀포시 중문관광로72번길 60",
    phoneNumber: "234-567-8901",
    homepage: "www.accommodation2.com",
    infoDetail: "This is a detail for Accommodation2",
    thumbnailUrl: "www.accommodation2.com/thumbnail.jpg",
    categoryParking: false,
    categoryCooking: true,
    categoryPickup: false,
    categoryAmenities: "aaa",
    categoryDiningArea: "bbb",
    checkIn: "14:00",
    checkOut: "14:00",
    wishCount: 20,
    viewCount: 201,
    isWish: false,
    lowest_price: 300,
    rooms: [
      {
        id: 3,
        name: "Room3",
        price: 300,
        capacity: 4,
        inventory: 0,
        categoryTv: true,
        categoryPc: true,
        categoryInternet: true,
        categoryRefrigerator: false,
        categoryBathingFacilities: false,
        categoryDryer: true,
        roomImages: [""],
      },
      {
        id: 4,
        name: "Room4",
        price: 400,
        capacity: 1,
        inventory: 3,
        categoryTv: false,
        categoryPc: false,
        categoryInternet: true,
        categoryRefrigerator: true,
        categoryBathingFacilities: true,
        categoryDryer: false,
        roomImages: [""],
      },
    ],
  },
};

exports.accommodationList = {
  message: "성공",
  data: [
    {
      id: 1,
      name: "Accommodation1",
      type: 3,
      address: "경상남도 하동군 화개로 13",
      phoneNumber: "123-456-7890",
      homepage: "www.accommodation1.com",
      infoDetail: "This is a detail for Accommodation1",
      thumbnailUrl: "www.accommodation1.com/thumbnail.jpg",
      categoryParking: true,
      categoryCooking: false,
      categoryPickup: true,
      categoryAmenities: "aaa",
      categoryDiningArea: "bbb",
      checkIn: "14:00",
      checkOut: "16:00",
      wishCount: 10,
      isWish: false,
      lowest_price: 100,
      viewCount: 101,
    },
    {
      id: 4,
      name: "Accommodation4",
      type: 1,
      address: "전라남도 무안군 현경면 홀통길 55",
      phoneNumber: "456-789-0123",
      homepage: "www.accommodation4.com",
      infoDetail: "This is a detail for Accommodation4",
      thumbnailUrl: "www.accommodation4.com/thumbnail.jpg",
      categoryParking: false,
      categoryCooking: false,
      categoryPickup: true,
      categoryAmenities: "aaa",
      categoryDiningArea: "bbb",
      checkIn: "14:00",
      checkOut: "14:00",
      wishCount: 41,
      isWish: true,
      lowest_price: 700,
      viewCount: 400,
    },
    {
      id: 7,
      name: "Accommodation7",
      type: 0,
      address: "경기도 수원시 팔달로 13",
      phoneNumber: "123-456-7890",
      homepage: "www.accommodation7.com",
      infoDetail: "This is a detail for Accommodation7",
      thumbnailUrl: "www.accommodation7.com/thumbnail.jpg",
      categoryParking: true,
      categoryCooking: false,
      categoryPickup: true,
      categoryAmenities: "aaa",
      categoryDiningArea: "bbb",
      checkIn: "15:00",
      checkOut: "11:00",
      wishCount: 10,
      isWish: false,
      lowest_price: 100,
      viewCount: 100,
    },
    {
      id: 10,
      name: "Accommodation10",
      type: 2,
      address: "서울특별시 강남구 강남대로 123",
      phoneNumber: "987-654-3210",
      homepage: "www.accommodation10.com",
      infoDetail: "This is a detail for Accommodation10",
      thumbnailUrl: "www.accommodation10.com/thumbnail.jpg",
      categoryParking: true,
      categoryCooking: true,
      categoryPickup: false,
      categoryAmenities: "ccc",
      categoryDiningArea: "ddd",
      checkIn: "12:00",
      checkOut: "10:00",
      wishCount: 25,
      isWish: true,
      lowest_price: 300,
      viewCount: 200,
    },
  ],
};

exports.roomList = {
  message: "성공",
  data: [
    {
      id: 12,
      accommodationName: "Accommodation7",
      name: "Room12",
      price: 200,
      capacity: 3,
      inventory: 5,
      categoryTv: false,
      categoryPc: true,
      categoryInternet: false,
      categoryRefrigerator: true,
      categoryBathingFacilities: true,
      categoryDryer: false,
    },
    {
      id: 13,
      accommodationName: "Accommodation3",
      name: "Room8",
      price: 150,
      capacity: 2,
      inventory: 3,
      categoryTv: true,
      categoryPc: false,
      categoryInternet: true,
      categoryRefrigerator: false,
      categoryBathingFacilities: true,
      categoryDryer: true,
    },
    {
      id: 14,
      accommodationName: "Accommodation5",
      name: "Room5",
      price: 180,
      capacity: 4,
      inventory: 7,
      categoryTv: true,
      categoryPc: true,
      categoryInternet: false,
      categoryRefrigerator: true,
      categoryBathingFacilities: false,
      categoryDryer: true,
    },
    {
      id: 15,
      accommodationName: "Accommodation2",
      name: "Room15",
      price: 250,
      capacity: 2,
      inventory: 2,
      categoryTv: false,
      categoryPc: true,
      categoryInternet: true,
      categoryRefrigerator: false,
      categoryBathingFacilities: true,
      categoryDryer: false,
    },
  ],
};
