exports.basketList = {
  message: "장바구니 조회 성공",
  data: {
    id: 1,
    totalPrice: 300,
    totalCount: 3,
    rooms: [
      {
        id: 1,
        accommodationName: "Accommodation1",
        roomName: "Room1",
        price: 100,
        numberOfGuests: 3,
        checkInAt: "2023-12-24",
        checkOutAt: "2023-12-25",
        roomUrl: null,
      },
      {
        id: 2,
        accommodationName: "Accommodation2",
        roomName: "Room1",
        price: 100,
        numberOfGuests: 1000,
        checkInAt: "2023-12-24",
        checkOutAt: "2023-12-25",
        roomUrl: null,
      },
      {
        id: 3,
        accommodationName: "Accommodation3",
        roomName: "Room1",
        price: 100,
        numberOfGuests: 3,
        checkInAt: "2023-12-24",
        checkOutAt: "2023-12-25",
        roomUrl: null,
      },
      {
        id: 4,
        accommodationName: "Accommodation4",
        roomName: "Room1",
        price: 100,
        numberOfGuests: 3,
        checkInAt: "2023-12-24",
        checkOutAt: "2023-12-25",
        roomUrl: null,
      },
      {
        id: 5,
        accommodationName: "Accommodation5",
        roomName: "Room1",
        price: 100,
        numberOfGuests: 3,
        checkInAt: "2023-12-24",
        checkOutAt: "2023-12-25",
        roomUrl: null,
      },
      {
        id: 6,
        accommodationName: "Accommodation6",
        roomName: "Room1",
        price: 100,
        numberOfGuests: 3,
        checkInAt: "2023-12-24",
        checkOutAt: "2023-12-25",
        roomUrl: null,
      },
    ],
  },
};
