exports.odersData = {
  message: "주문 상세 조회 완료",
  data: {
    id: 1,
    totalPrice: 200,
    totalCount: 3,
    orderAt: "2023-11-29T16:29:54.190297",
    rooms: [
      {
        id: 1,
        accommodationName: "Accommodation7",
        roomName: "Room12",
        price: 200,
        numberOfGuests: 3,
        checkInAt: "2023-12-24",
        checkOutAt: null,
        roomUrl: "",
      },
      {
        id: 2,
        accommodationName: "Accommodation3",
        roomName: "Room8",
        price: 150,
        numberOfGuests: 2,
        checkInAt: "2023-12-25",
        checkOutAt: "2023-12-27",
        roomUrl: "",
      },
      {
        id: 3,
        accommodationName: "Accommodation5",
        roomName: "Room5",
        price: 180,
        numberOfGuests: 4,
        checkInAt: "2023-12-28",
        checkOutAt: "2023-12-31",
        roomUrl: "",
      },
      {
        id: 4,
        accommodationName: "Accommodation2",
        roomName: "Room15",
        price: 250,
        numberOfGuests: 2,
        checkInAt: "2023-12-30",
        checkOutAt: "2024-01-02",
        roomUrl: "",
      },
    ],
  },
};
