exports.wishList = {
  message: "좋아요 리스트 조회 성공",
  data: [
    {
      accommodation: {
        id: 2,
        name: "Accommodation2",
        type: 0,
        address: "제주특별자치도 서귀포시 중문관광로72번길 60",
        phoneNumber: "234-567-8901",
        homepage: "www.accommodation2.com",
        infoDetail: "This is a detail for Accommodation2",
        thumbnailUrl: "www.accommodation2.com/thumbnail.jpg",
        categoryParking: false,
        categoryCooking: true,
        categoryPickup: false,
        categoryAmenities: "aaa",
        categoryDiningArea: "bbb",
        checkIn: "14:00",
        checkOut: "14:00",
        wishCount: 21,
        isWish: null,
        lowest_price: null,
        viewCount: 201,
      },
    },
    {
      accommodation: {
        id: 3,
        name: "Accommodation3",
        type: 1,
        address: "서울특별시 종로구 자하문로5가길 11 (체부동)",
        phoneNumber: "345-678-9012",
        homepage: "www.accommodation3.com",
        infoDetail: "This is a detail for Accommodation3",
        thumbnailUrl: "www.accommodation3.com/thumbnail.jpg",
        categoryParking: true,
        categoryCooking: true,
        categoryPickup: false,
        categoryAmenities: "aaa",
        categoryDiningArea: "bbb",
        checkIn: "14:00",
        checkOut: "14:00",
        wishCount: 31,
        isWish: null,
        lowest_price: null,
        viewCount: 300,
      },
    },
    {
      accommodation: {
        id: 4,
        name: "Accommodation4",
        type: 1,
        address: "전라남도 무안군 현경면 홀통길 55",
        phoneNumber: "456-789-0123",
        homepage: "www.accommodation4.com",
        infoDetail: "This is a detail for Accommodation4",
        thumbnailUrl: "www.accommodation4.com/thumbnail.jpg",
        categoryParking: false,
        categoryCooking: false,
        categoryPickup: true,
        categoryAmenities: "aaa",
        categoryDiningArea: "bbb",
        checkIn: "14:00",
        checkOut: "14:00",
        wishCount: 41,
        isWish: null,
        lowest_price: null,
        viewCount: 400,
      },
    },
  ],
};
